name: Docs v2 Feedback Form
description: Use this form to give us feedback on Docs v2. Be as detailed as you can. If your feedback
  is about a specific page or area, please be sure to include a link. '
title: '[Docs-V2-Feedback]'
labels:
  - docs-v2-feedback
body:
  - type: dropdown
    id: type
    attributes:
      label: Category
      description: Please choose the category that best describes your needs.
      options:
        - Error
        - Enhancement
        - Missing Content
        - Other
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your email address
      placeholder: john@doe.com
    validations:
      required: false
  - type: input
    id: issue-location
    attributes:
      label: Location in Docs
      placeholder: '[docs.casper.network/home]'
      description: Where in the docs is this issue. If there is no location, leave the placeholder.
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Description
      placeholder: Please describe your issue here.
      description: Please provide a detailed description of your issue.
    validations:
      required: true
  - type: textarea
    id: attachments
    attributes:
      label: Attachments (optional)
      description: Please attach any logs, screenshots, or links that may help with the analysis.
    validations:
      required: false